enum CountryCodeISO3166: Int {
    
    case afghanistan = 004
    case albania = 008
    case algeria = 012
    case andorra = 020
    case angola = 024
    case antiguaAndBarbuda = 028
    case argentina = 032
    case armenia = 051
    case australia = 036
    case austria = 040
    case azerbaijan = 031
    case bahamas = 044
    case bahrain = 048
    case bangladesh = 050
    case barbados = 052
    case belarus = 112
    case belgium = 056
    case belize = 084
    case benin = 204
    case bhutan = 064
    case bolivia = 068
    case bosniaAndHerzegovina = 070
    case botswana = 072
    case brazil = 076
    case brunei = 096
    case bulgaria = 100
    case burkinaFaso = 854
    case burundi = 108
    case capeVerde = 132
    case cambodia = 116
    case cameroon = 120
    case canada = 124
    case centralAfricanRepublic = 140
    case chad = 148
    case chile = 152
    case china = 156
    case colombia = 170
    case comoros = 174
    case congo = 178
    case democraticRepublicOfTheCongo = 180
    case costaRica = 188
    case croatia = 191
    case cuba = 192
    case cyprus = 196
    case czechRepublic = 203
    case denmark = 208
    case djibouti = 262
    case dominica = 212
    case dominicanRepublic = 214
    case ecuador = 218
    case egypt = 818
    case elSalvador = 222
    case equatorialGuinea = 226
    case eritrea = 232
    case estonia = 233
    case eswatini = 748
    case ethiopia = 231
    case fiji = 242
    case finland = 246
    case france = 250
    case gabon = 266
    case gambia = 270
    case georgia = 268
    case germany = 276
    case ghana = 288
    case greece = 300
    case grenada = 308
    case guatemala = 320
    case guinea = 324
    case guineaBissau = 624
    case guyana = 328
    case haiti = 332
    case honduras = 340
    case hungary = 348
    case iceland = 352
    case india = 356
    case indonesia = 360
    case iran = 364
    case iraq = 368
    case ireland = 372
    case israel = 376
    case italy = 380
    case ivoryCoast = 384
    case jamaica = 388
    case japan = 392
    case jordan = 400
    case kazakhstan = 398
    case kenya = 404
    case kiribati = 296
    case koreaNorth = 408
    case koreaSouth = 410
    case kosovo = 383
    case kuwait = 414
    case kyrgyzstan = 417
    case laos = 418
    case latvia = 428
    case lebanon = 422
    case lesotho = 426
    case liberia = 430
    case libya = 434
    case liechtenstein = 438
    case lithuania = 440
    case luxembourg = 442
    case madagascar = 450
    case malawi = 454
    case malaysia = 458
    case maldives = 462
    case mali = 466
    case malta = 470
    case marocco = 504
    case marshallIslands = 584
    case mauritania = 478
    case mauritius = 480
    case mexico = 484
    case micronesia = 583
    case moldova = 498
    case monaco = 492
    case mongolia = 496
    case montenegro = 499
    case mozambique = 508
    case myanmar = 104
    case namibia = 516
    case nauru = 520
    case nepal = 524
    case netherlands = 528
    case newZealand = 554
    case nicaragua = 588
    case niger = 562
    case nigeria = 566
    case northMacedonia = 807
    case norway = 578
    case oman = 512
    case pakistan = 586
    case palau = 585
    case palestine = 275
    case panama = 591
    case papuaNewGuinea = 598
    case paraguay = 600
    case peru = 604
    case philippines = 608
    case poland = 616
    case portugal = 620
    case qatar = 634
    case romania = 642
    case russia = 643
    case rwanda = 646
    case saintKittsAndNevis = 659
    case saintLucia = 662
    case saintVincentAndTheGrenadines = 670
    case samoa = 882
    case sanMarino = 674
    case saudiArabia = 682
    case senegal = 686
    case serbia = 688
    case seychelles = 690
    case sierraLeone = 694
    case singapore = 702
    case slovakia = 703
    case slovenia = 705
    case solomonIslands = 090
    case somalia = 706
    case southAfrica = 710
    case southSudan = 728
    case spain = 724
    case sriLanka = 144
    case sudan = 729
    case suriname = 740
    case sweden = 752
    case switzerland = 756
    case syria = 760
    case taiwan = 158
    case tajikistan = 762
    case tanzania = 834
    case thailand = 764
    case timorLeste = 626
    case togo = 768
    case tonga = 776
    case trinidadAndTobago = 780
    case tunisia = 788
    case turkey = 792
    case turkmenistan = 795
    case tuvalu = 798
    case uganda = 800
    case ukraine = 804
    case unitedArabEmirates = 784
    case unitedKingdom = 826
    case unitedStates = 840
    case uruguay = 858
    case uzbekistan = 860
    case vanuatu = 548
    case vaticanCity = 336
    case venezuela = 862
    case vietnam = 704
    case yemen = 887
    case zambia = 894
    case zimbabwe = 716
    
    var alpha2: String {
        switch self {
        case .afghanistan: return "AF"
        case .albania: return "AL"
        case .algeria: return "DZ"
        case .andorra: return "AD"
        case .angola: return "AO"
        case .antiguaAndBarbuda: return "AG"
        case .argentina: return "AR"
        case .armenia: return "AM"
        case .australia: return "AU"
        case .austria: return "AT"
        case .azerbaijan: return "AZ"
        case .bahamas: return "BS"
        case .bahrain: return "BH"
        case .bangladesh: return "BD"
        case .barbados: return "BB"
        case .belarus: return "BY"
        case .belgium: return "BE"
        case .belize: return "BZ"
        case .benin: return "BJ"
        case .bhutan: return "BT"
        case .bolivia: return "BO"
        case .bosniaAndHerzegovina: return "BA"
        case .botswana: return "BW"
        case .brazil: return "BR"
        case .brunei: return "BN"
        case .bulgaria: return "BG"
        case .burkinaFaso: return "BF"
        case .burundi: return "BI"
        case .capeVerde: return "CV"
        case .cambodia: return "KH"
        case .cameroon: return "CM"
        case .canada: return "CA"
        case .centralAfricanRepublic: return "CF"
        case .chad: return "TD"
        case .chile: return "CL"
        case .china: return "CN"
        case .colombia: return "CO"
        case .comoros: return "KM"
        case .congo: return "CG"
        case .democraticRepublicOfTheCongo: return "CD"
        case .costaRica: return "CR"
        case .croatia: return "HR"
        case .cuba: return "CU"
        case .cyprus: return "CY"
        case .czechRepublic: return "CZ"
        case .denmark: return "DK"
        case .djibouti: return "DJ"
        case .dominica: return "DM"
        case .dominicanRepublic: return "DO"
        case .ecuador: return "EC"
        case .egypt: return "EG"
        case .elSalvador: return "SV"
        case .equatorialGuinea: return "GQ"
        case .eritrea: return "ER"
        case .estonia: return "EE"
        case .eswatini: return "SZ"
        case .ethiopia: return "ET"
        case .fiji: return "FJ"
        case .finland: return "FI"
        case .france: return "FR"
        case .gabon: return "GA"
        case .gambia: return "GM"
        case .georgia: return "GE"
        case .germany: return "DE"
        case .ghana: return "GH"
        case .greece: return "GR"
        case .grenada: return "GD"
        case .guatemala: return "GT"
        case .guinea: return "GN"
        case .guineaBissau: return "GW"
        case .guyana: return "GY"
        case .haiti: return "HT"
        case .honduras: return "HN"
        case .hungary: return "HU"
        case .iceland: return "IS"
        case .india: return "IN"
        case .indonesia: return "ID"
        case .iran: return "IR"
        case .iraq: return "IQ"
        case .ireland: return "IE"
        case .israel: return "IL"
        case .italy: return "IT"
        case .ivoryCoast: return "CI"
        case .jamaica: return "JM"
        case .japan: return "JP"
        case .jordan: return "JO"
        case .kazakhstan: return "KZ"
        case .kenya: return "KE"
        case .kiribati: return "KI"
        case .koreaNorth: return "KP"
        case .koreaSouth: return "KR"
        case .kosovo: return "XK"
        case .kuwait: return "KW"
        case .kyrgyzstan: return "KG"
        case .laos: return "LA"
        case .latvia: return "LV"
        case .lebanon: return "LB"
        case .lesotho: return "LS"
        case .liberia: return "LR"
        case .libya: return "LY"
        case .liechtenstein: return "LI"
        case .lithuania: return "LT"
        case .luxembourg: return "LU"
        case .madagascar: return "MG"
        case .malawi: return "MW"
        case .malaysia: return "MY"
        case .maldives: return "MV"
        case .mali: return "ML"
        case .malta: return "MT"
        case .marocco: return "MA"
        case .marshallIslands: return "MH"
        case .mauritania: return "MR"
        case .mauritius: return "MU"
        case .mexico: return "MX"
        case .micronesia: return "FM"
        case .moldova: return "MD"
        case .monaco: return "MC"
        case .mongolia: return "MN"
        case .montenegro: return "ME"
        case .mozambique: return "MZ"
        case .myanmar: return "MM"
        case .namibia: return "NA"
        case .nauru: return "NR"
        case .nepal: return "NP"
        case .netherlands: return "NL"
        case .newZealand: return "NZ"
        case .nicaragua: return "NI"
        case .niger: return "NE"
        case .nigeria: return "NG"
        case .northMacedonia: return "MK"
        case .norway: return "NO"
        case .oman: return "OM"
        case .pakistan: return "PK"
        case .palau: return "PW"
        case .palestine: return "PS"
        case .panama: return "PA"
        case .papuaNewGuinea: return "PG"
        case .paraguay: return "PY"
        case .peru: return "PE"
        case .philippines: return "PH"
        case .poland: return "PL"
        case .portugal: return "PT"
        case .qatar: return "QA"
        case .romania: return "RO"
        case .russia: return "RU"
        case .rwanda: return "RW"
        case .saintKittsAndNevis: return "KN"
        case .saintLucia: return "LC"
        case .saintVincentAndTheGrenadines: return "VC"
        case .samoa: return "WS"
        case .sanMarino: return "SM"
        case .saudiArabia: return "SA"
        case .senegal: return "SN"
        case .serbia: return "RS"
        case .seychelles: return "SC"
        case .sierraLeone: return "SL"
        case .singapore: return "SG"
        case .slovakia: return "SK"
        case .slovenia: return "SI"
        case .solomonIslands: return "SB"
        case .somalia: return "SO"
        case .southAfrica: return "ZA"
        case .southSudan: return "SS"
        case .spain: return "ES"
        case .sriLanka: return "LK"
        case .sudan: return "SD"
        case .suriname: return "SR"
        case .sweden: return "SE"
        case .switzerland: return "CH"
        case .syria: return "SY"
        case .taiwan: return "TW"
        case .tajikistan: return "TJ"
        case .tanzania: return "TZ"
        case .thailand: return "TH"
        case .timorLeste: return "TL"
        case .togo: return "TG"
        case .tonga: return "TO"
        case .trinidadAndTobago: return "TT"
        case .tunisia: return "TN"
        case .turkey: return "TR"
        case .turkmenistan: return "TM"
        case .tuvalu: return "TV"
        case .uganda: return "UG"
        case .ukraine: return "UA"
        case .unitedArabEmirates: return "AE"
        case .unitedKingdom: return "GB"
        case .unitedStates: return "US"
        case .uruguay: return "UY"
        case .uzbekistan: return "UZ"
        case .vanuatu: return "VU"
        case .vaticanCity: return "VA"
        case .venezuela: return "VE"
        case .vietnam: return "VN"
        case .yemen: return "YE"
        case .zambia: return "ZM"
        case .zimbabwe: return "ZW"
        }
    }
    
    static func numericToAlpha2(numericCode: Int) -> String? {
        guard let countryCode = CountryCodeISO3166(rawValue: numericCode) else {
            return nil
        }
        return countryCode.alpha2
    }
}
